name: Comprehensive Tests

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  UI-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install dependencies
        run: npm install

      - name: Install browser dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libnss3 libatk-bridge2.0-0 libxcomposite1 libxrandr2

      - name: Run Cypress Tests in Headed Mode
        run: npm run test

      - name: Generate and Upload Report
        run: npm run generate-report

      - name: Upload UI Test Report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: mochawesome-report
          path: cypress/reports/mochawesome-report
